spring.application.name=planillas
server.port=${PORT:8080}

# 1. SOLUCIÓN PARA EL TENANT NOT FOUND (Usuario y password van DENTRO de la URL)
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. SOLUCIÓN PARA EL DIALECTO (Le decimos directamente que es PostgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect    
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Mantenemos tus configuraciones de esquema
spring.jpa.properties.hibernate.default_schema=finanzas
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true